### PR TITLE
Merge govips upstream

### PR DESCRIPTION
**Pull request by alon-ne**

### CODE REVIEW

**Review by Elad-Laufer — CHANGES_REQUESTED** [review]
please re-merge

**Comment by alon-ne** [comment]
> please re-merge

re-merge what where?

**Comment by Elad-Laufer** [comment]
> > please re-merge
> 
> re-merge what where?

the latest from upstream

**Review by Elad-Laufer — APPROVED** [review]
please merge the latest from upstream before merging into our master

**Comment by alon-ne** [comment]
> please merge the latest from upstream before merging into our master

I checked now, there's nothing new there

**Comment by alon-ne** [comment]
> please merge the latest from upstream before merging into our master

There's nothing new there, checked now

**Pull request merged**
